In [ ]:
# numpy - numberical python

- numpy provide the convient and efficent way to handle large amount of data
- very fast
- used for computation and processing of single dim or multi dimension arrays
- it a extend module in python written in c
- all the elements should be homeogenous

In [1]:
import numpy as np

1. Create an array using

In [2]:
# list

lst = [1,3,5,7,9]

arr = np.array(lst)

print(arr, type(arr))

[1 3 5 7 9] <class 'numpy.ndarray'>


In [ ]:
array - 0 ---> scalar
array - 1 ---> 1d / vector
array - 2 ---> 2d (rows and columns)
array - 3 ---> 3d (rows, columns, height)
array - n ---> nd array

In [4]:
arr

array([1, 3, 5, 7, 9])

In [5]:
# imoprtand attritbutes

# size --> number of element in array
print(arr.size)

5


In [6]:
# shape --> gives the dimension about an array
print(arr.shape)

(5,)


In [7]:
# ndim

print(arr.ndim)

1


In [8]:
lst = [[1,3,5],[7,9,10]]

arr = np.array(lst)

print(arr, type(arr))

[[ 1  3  5]
 [ 7  9 10]] <class 'numpy.ndarray'>


In [9]:
print(arr.size)

6


In [10]:
print(arr.shape)

(2, 3)


In [11]:
print(arr.ndim)

2


In [12]:
# 2. arange function --> output --> array

# np.arange(start,stop,step)

np.arange(0,56,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54])

In [14]:
# 3. zeros

print(np.zeros((4,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
# 4.ones

print(np.ones((4,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
# 5. identity matrix

# - 0 and 1
# - dig will be 1
# - sqaure - rows == columns

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Reshaping - converting from any dim to any other dim

In [17]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [18]:
# 2d

# rule

# it should accomodate all the elements

# 1,6
# 3,2
# 2,3
# 6,1 --> number of elements

a.reshape((1,6))

array([[0, 1, 2, 3, 4, 5]])

In [19]:
a.reshape((6,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [20]:
a.reshape((3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
a.reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 3 -dim

3,2,1
6,1,1
1,1,6

In [27]:
a.reshape((2,3,1,1,1,1))

array([[[[[[0]]]],



        [[[[1]]]],



        [[[[2]]]]],




       [[[[[3]]]],



        [[[[4]]]],



        [[[[5]]]]]])

In [23]:
Asian_countries = np.array(["India","Pakistan",
                            "China","Japan",
                            "Sri Lanka","Thailand",
                            "Bangladesh","Myanmar"])
print(Asian_countries)

['India' 'Pakistan' 'China' 'Japan' 'Sri Lanka' 'Thailand' 'Bangladesh'
 'Myanmar']


In [28]:
Asian_countries.reshape((2,6))

ValueError: cannot reshape array of size 8 into shape (2,6)

In [29]:
Asian_countries

array(['India', 'Pakistan', 'China', 'Japan', 'Sri Lanka', 'Thailand',
       'Bangladesh', 'Myanmar'], dtype='<U10')

In [ ]:
# infer

n dim data ----> convert to 2 dim in such a way that the number of column should be 10

(100,2,4,5) ---> 2d ---> column be 10

In [34]:
array = np.arange(4000).reshape(100,2,4,5)

In [36]:
array.shape

(100, 2, 4, 5)

In [38]:
data = array.reshape((-1,10))

In [39]:
data.shape

(400, 10)

In [ ]:
i want array from 100,2,4,5 to be converted to 2 dim in such a way that numner of rows
should be 50 --> 50,-1

i want array from 100,2,4,5 to be converted to 3 dim in such a way that numner of rows
should be 2 and col should be 20

2,20,-1

In [40]:
data = array.reshape((-1,10,-1))

ValueError: can only specify one unknown dimension

In [48]:
# traspose row,column

data = Asian_countries.reshape(4,2,1)

In [49]:
data

array([[['India'],
        ['Pakistan']],

       [['China'],
        ['Japan']],

       [['Sri Lanka'],
        ['Thailand']],

       [['Bangladesh'],
        ['Myanmar']]], dtype='<U10')

In [50]:
data.shape

(4, 2, 1)

In [51]:
data_2 = data.T

In [52]:
data_2.shape

(1, 2, 4)

In [ ]:
# flatten --> any dimesnion ---> 1 dim

In [53]:
array = np.arange(4000).reshape(100,2,4,5)

In [54]:
array.flatten()

array([   0,    1,    2, ..., 3997, 3998, 3999])

In [55]:
array

array([[[[   0,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19]],

        [[  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29],
         [  30,   31,   32,   33,   34],
         [  35,   36,   37,   38,   39]]],


       [[[  40,   41,   42,   43,   44],
         [  45,   46,   47,   48,   49],
         [  50,   51,   52,   53,   54],
         [  55,   56,   57,   58,   59]],

        [[  60,   61,   62,   63,   64],
         [  65,   66,   67,   68,   69],
         [  70,   71,   72,   73,   74],
         [  75,   76,   77,   78,   79]]],


       [[[  80,   81,   82,   83,   84],
         [  85,   86,   87,   88,   89],
         [  90,   91,   92,   93,   94],
         [  95,   96,   97,   98,   99]],

        [[ 100,  101,  102,  103,  104],
         [ 105,  106,  107,  108,  109],
         [ 110,  111,  112,  113,  114],
         [ 115,  116,  117,  118,  119]]],


# basic operations

In [57]:
a = np.array([10,20,30,40])
b = np.array([1,2,36,49])

In [58]:
a+b

array([11, 22, 66, 89])

In [61]:
a = np.array([10,20,30,40])
b = np.array([1,2,36,49])

In [62]:
a-b

array([ 9, 18, -6, -9])

In [63]:
a*b

array([  10,   40, 1080, 1960])

In [64]:
a/b

array([10.        , 10.        ,  0.83333333,  0.81632653])

In [65]:
a%2

array([0, 0, 0, 0])

In [66]:
a>15

array([False,  True,  True,  True])

In [ ]:
# matrix muplication --> dot product

a = n*m
b = m*q

c = n*q

In [67]:
array_1 = np.array([[1,2,3],[4,5,6]])
array_2 = np.array([[1,7],[6,8],[9,9]])

In [68]:
array_1.shape

(2, 3)

In [69]:
array_2.shape

(3, 2)

In [70]:
array_1.dot(array_2)

array([[ 40,  50],
       [ 88, 122]])

In [71]:
# unary operation

data = np.array([10,20,30,32,12,34,56,78,90,112,34,45])

In [72]:
# sum of all the elemenst

data.sum()

553

In [73]:
# min of all the elements

data.min()

10

In [74]:
# max of all the elements

data.max()

112

In [75]:
data.size

12

In [76]:
new_data = data.reshape(3,4)

In [77]:
new_data

array([[ 10,  20,  30,  32],
       [ 12,  34,  56,  78],
       [ 90, 112,  34,  45]])

In [ ]:
# sum

1 --> cal sum of all the elements
2 --> cal the sum of all the indivual rows
3 --> cal the sum of all the indivisual column

# axis - 0 --> column
       - 1 ---> row

In [78]:
new_data.sum()

553

In [79]:
new_data.sum(axis=1)

array([ 92, 180, 281])

In [80]:
new_data.sum(axis=0)

array([112, 166, 120, 155])

In [ ]:
# max

1 --> cal max of all the elements
2 --> cal the max of all the indivual rows
3 --> cal the max of all the indivisual column

# axis - 0 --> column
       - 1 ---> row

In [ ]:
new_data.max()
new_data.max(axis=1)
new_data.max(axis=0)

In [ ]:
# min

1 --> cal min of all the elements
2 --> cal the min of all the indivual rows
3 --> cal the min of all the indivisual column

# axis - 0 --> column
       - 1 ---> row
    

In [81]:
new_data.min()
new_data.min(axis=1)
new_data.min(axis=0)

array([10, 20, 30, 32])