In [1]:
# indexing and slicing

In [2]:
import numpy as np

In [3]:
a = np.arange(5)*2

In [4]:
a

array([0, 2, 4, 6, 8])

In [5]:
# indexing

a[0]

0

In [6]:
# -ve indexing
a[-2]

6

In [7]:
# slicing a[start:stop:step]

a[::-1]

array([8, 6, 4, 2, 0])

In [8]:
#. 2 dim

a1 = np.arange(25).reshape(5,5)

In [9]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
# indexing

a1[2][-2]

13

In [13]:
a1[2][3]

13

In [14]:
# slicing - a1[start:stop:step, start:stop:step] --> a1[row,column]

a1[2:3:1,1:4:1]

array([[11, 12, 13]])

In [15]:
a1[:2,1:3]

array([[1, 2],
       [6, 7]])

In [16]:
# 11 12
# 16 17

# identify the rows
a1[2:4]

# identiy the columns

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
a1[2:4,1:3]

array([[11, 12],
       [16, 17]])

In [18]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
# 6   7
# 16  17

a1[1:4:2]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [20]:
a1[1:4:2, 1:3]

array([[ 6,  7],
       [16, 17]])

In [21]:
# 5     7    9

# 15   17   19

a1[1:4:2,::2]

array([[ 5,  7,  9],
       [15, 17, 19]])

In [22]:
# iterating over arrays

a

array([0, 2, 4, 6, 8])

In [23]:
for element in a:
    print(element)

0
2
4
6
8


In [24]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
for elements in a1:
    print(elements)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [26]:
for rows in a1:
    for element in rows:
        print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [29]:
for element in a1.flatten():
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


# splitting of an array

In [ ]:
np.split(array, int/list of int, axis)

In [30]:
a = np.arange(10)*11.2

In [31]:
a

array([  0. ,  11.2,  22.4,  33.6,  44.8,  56. ,  67.2,  78.4,  89.6,
       100.8])

In [33]:
# option 1 int
# np.split(array, int, axis)

# rule when using int --- int value should be divisble by total number of elements in an array

np.split(a,5)

[array([ 0. , 11.2]),
 array([22.4, 33.6]),
 array([44.8, 56. ]),
 array([67.2, 78.4]),
 array([ 89.6, 100.8])]

In [34]:
np.split(a,8)

ValueError: array split does not result in an equal division

In [36]:
a

array([  0. ,  11.2,  22.4,  33.6,  44.8,  56. ,  67.2,  78.4,  89.6,
       100.8])

In [35]:
# option 2 list of int
# np.split(array, [int], axis)


np.split(a,[3,6,9,12])

# 0-3 - 0,1,2
# 3-6 - 3,4,5
# 6-9 - 6,7,8
# 9-12- 9,10,11
# 12-+- 12 and more

[array([ 0. , 11.2, 22.4]),
 array([33.6, 44.8, 56. ]),
 array([67.2, 78.4, 89.6]),
 array([100.8]),
 array([], dtype=float64)]

In [37]:
np.split(a,[1,3,7,10])

# how may splits

# 0-1 - 0
# 1-3 - 1,2
# 3-7 - 3,4,5,6
# 7-10 - 7,8,9
# 10-+ - 10 and +

[array([0.]),
 array([11.2, 22.4]),
 array([33.6, 44.8, 56. , 67.2]),
 array([ 78.4,  89.6, 100.8]),
 array([], dtype=float64)]

In [38]:
np.split(a,[1,3,7])

# how may splits

# 0-1 - 0
# 1-3 - 1,2
# 3-7 - 3,4,5,6
# 7or more - 7,8,9 and +

[array([0.]),
 array([11.2, 22.4]),
 array([33.6, 44.8, 56. , 67.2]),
 array([ 78.4,  89.6, 100.8])]

In [39]:
np.split(a,[1,3,7,1,2,4,5,6])

[array([0.]),
 array([11.2, 22.4]),
 array([33.6, 44.8, 56. , 67.2]),
 array([], dtype=float64),
 array([11.2]),
 array([22.4, 33.6]),
 array([44.8]),
 array([56.]),
 array([ 67.2,  78.4,  89.6, 100.8])]

In [41]:
a.reshape(5,2)

array([[  0. ,  11.2],
       [ 22.4,  33.6],
       [ 44.8,  56. ],
       [ 67.2,  78.4],
       [ 89.6, 100.8]])

In [42]:
np.split(a,5)

[array([ 0. , 11.2]),
 array([22.4, 33.6]),
 array([44.8, 56. ]),
 array([67.2, 78.4]),
 array([ 89.6, 100.8])]

In [45]:
data = np.arange(36).reshape(4,9)

In [46]:
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [ ]:
axis -1 --> column wise split
axis -0 --> row wise split

In [49]:
# option 1 - int

# rule when using int --- int value should be divisble by total number columns in an array

np.split(data,2,1)

ValueError: array split does not result in an equal division

In [50]:
# rule when using int --- int value should be divisble by total number of rows in an array
np.split(data,2,0)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]])]

In [51]:
# option 2 - [int]

np.split(data,[2,3,5,8],1)

# True,false
# how many splits
# which all columbs will be includes

# 0-2 - 0,1
# 2-3 - 2
# 3-5 - 3,4
# 5-8 - 5,6,7
# 8-more - 8 and more

[array([[ 0,  1],
        [ 9, 10],
        [18, 19],
        [27, 28]]),
 array([[ 2],
        [11],
        [20],
        [29]]),
 array([[ 3,  4],
        [12, 13],
        [21, 22],
        [30, 31]]),
 array([[ 5,  6,  7],
        [14, 15, 16],
        [23, 24, 25],
        [32, 33, 34]]),
 array([[ 8],
        [17],
        [26],
        [35]])]

In [53]:
np.split(data,[2,3,5,8],0)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([[27, 28, 29, 30, 31, 32, 33, 34, 35]]),
 array([], shape=(0, 9), dtype=int64),
 array([], shape=(0, 9), dtype=int64)]

In [52]:
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [54]:
# alternative

np.hsplit(data,[2,3,5,8])

[array([[ 0,  1],
        [ 9, 10],
        [18, 19],
        [27, 28]]),
 array([[ 2],
        [11],
        [20],
        [29]]),
 array([[ 3,  4],
        [12, 13],
        [21, 22],
        [30, 31]]),
 array([[ 5,  6,  7],
        [14, 15, 16],
        [23, 24, 25],
        [32, 33, 34]]),
 array([[ 8],
        [17],
        [26],
        [35]])]

In [55]:
np.vsplit(data,[2,3,5,8])

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([[27, 28, 29, 30, 31, 32, 33, 34, 35]]),
 array([], shape=(0, 9), dtype=int64),
 array([], shape=(0, 9), dtype=int64)]

In [ ]:
# vector stacking

In [58]:
a = np.array([["New York","Maryland"],["Albany","Annapolis"]])

b = np.array([["Ohio","Arizona"],["Columbus","Phoenix"]])

In [ ]:
# axis-->0--row-wise
# axis-->1--column wise

In [59]:
a

array([['New York', 'Maryland'],
       ['Albany', 'Annapolis']], dtype='<U9')

In [60]:
b

array([['Ohio', 'Arizona'],
       ['Columbus', 'Phoenix']], dtype='<U8')

In [61]:
np.concatenate((a,b),axis=0)

array([['New York', 'Maryland'],
       ['Albany', 'Annapolis'],
       ['Ohio', 'Arizona'],
       ['Columbus', 'Phoenix']], dtype='<U9')

In [62]:
np.concatenate((a,b),axis=1)

array([['New York', 'Maryland', 'Ohio', 'Arizona'],
       ['Albany', 'Annapolis', 'Columbus', 'Phoenix']], dtype='<U9')

In [65]:
a = np.array([["New York","Maryland","india"],["Albany","Annapolis",'Australia']])

b = np.array([["Ohio","Arizona"],["Columbus","Phoenix"]])

In [66]:
a

array([['New York', 'Maryland', 'india'],
       ['Albany', 'Annapolis', 'Australia']], dtype='<U9')

In [67]:
b

array([['Ohio', 'Arizona'],
       ['Columbus', 'Phoenix']], dtype='<U8')

In [68]:
# rowsie -- number of columns of both the matrix/array should be same
# column wise --> number of rows of both the matrix should be same

np.concatenate((a,b),axis=1)

array([['New York', 'Maryland', 'india', 'Ohio', 'Arizona'],
       ['Albany', 'Annapolis', 'Australia', 'Columbus', 'Phoenix']],
      dtype='<U9')

In [69]:
np.concatenate((a,b),axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [70]:
a = np.array([["New York","Maryland"],["Albany","Annapolis"],['india','Aus']])

b = np.array([["Ohio","Arizona"],["Columbus","Phoenix"]])

In [71]:
a

array([['New York', 'Maryland'],
       ['Albany', 'Annapolis'],
       ['india', 'Aus']], dtype='<U9')

In [72]:
b

array([['Ohio', 'Arizona'],
       ['Columbus', 'Phoenix']], dtype='<U8')

In [75]:
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [73]:
a.shape

(3, 2)

In [74]:
b.shape

(2, 2)

In [76]:
np.concatenate((a,b),axis=0)

array([['New York', 'Maryland'],
       ['Albany', 'Annapolis'],
       ['india', 'Aus'],
       ['Ohio', 'Arizona'],
       ['Columbus', 'Phoenix']], dtype='<U9')

In [ ]:
# tme session - image - pandas -intro